---
swagger: "2.0"
info:
  version: "2018-05-11T16:03:30Z"
  title: "imageresizetest"
host: "m4ks7val64.execute-api.us-west-2.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /{proxy+}:
    x-amazon-apigateway-any-method:
      produces:
      - "application/json"
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        type: "string"
      responses: {}
