AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  testimageresizeevetesteveresizeAVL1ITL7RWOG:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 3
      Policies:
        - AmazonS3FullAccess
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
      Environment:
        Variables:
          BUCKET: test-imageresize-eve
          URL: 'http://test-imageresize-eve.s3-website-us-west-2.amazonaws.com'
