version: 0.2
phases:
  install:
    commands:
      - cd lambda/imageresize-function
      - npm install
      - find ./node_modules/* -mtime +10950 -exec touch {} \;
      - aws cloudformation package --template-file function-template.yaml --s3-bucket eve-lambda
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - lambda/imageresize-function/function-template.yaml
    - lambda/imageresize-function/outputSamTemplate.yaml