version: 0.2
phases:
  install:
    commands:
      - npm install
      - find ./node_modules/* -mtime +10950 -exec touch {} \;
      - aws cloudformation package --template-file function-template.yaml --s3-bucket eve-lambda/image-resize
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - function-template.yaml
    - outputSamTemplate.yaml